# Translations template for heat.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the heat project.
#
# Translators:
# Rafael Rivero <rafael@cloudscaling.com>, 2014
msgid ""
msgstr ""
"Project-Id-Version: Heat\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-09-25 06:13+0000\n"
"PO-Revision-Date: 2014-09-13 23:49+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Spanish (http://www.transifex.com/projects/p/heat/language/"
"es/)\n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: heat/api/aws/ec2token.py:162
msgid "Ec2Token authorization failed, no auth_uri specified in config file"
msgstr ""
"Ec2Token autorización ha fallado, ningún auth_uri especificado en el archivo "
"de configuración"

#: heat/api/aws/utils.py:105
#, python-format
msgid "Request does not contain %s parameter!"
msgstr "Solicitud no contiene parámetro %s!"

#: heat/api/cloudwatch/watch.py:274
msgid "Request does not contain required MetricData"
msgstr "Solicitud no contiene el requisito MetricData"

#: heat/common/heat_keystoneclient.py:134
msgid "Admin client authentication failed"
msgstr "Ha fallado la autenticación del cliente de administración"

#: heat/common/heat_keystoneclient.py:154
msgid "Domain admin client authentication failed"
msgstr ""

#: heat/common/heat_keystoneclient.py:184
msgid "Unknown version in auth_token_info"
msgstr ""

#: heat/common/heat_keystoneclient.py:195
msgid "Keystone v3 API connection failed, no password trust or auth_token!"
msgstr ""

#: heat/common/heat_keystoneclient.py:211
msgid "trust token re-scoping failed!"
msgstr ""

#: heat/common/heat_keystoneclient.py:215
msgid "Trust impersonation failed"
msgstr ""

#: heat/common/heat_keystoneclient.py:338
#: heat/common/heat_keystoneclient.py:425
#, python-format
msgid "Failed to add user %(user)s to role %(role)s, check role exists!"
msgstr ""

#: heat/common/lifecycle_plugin_utils.py:43
msgid "failed to get lifecycle plug point classes"
msgstr "fallo a obtener clases de punto de conexión de ciclo de vida "

#: heat/common/lifecycle_plugin_utils.py:50
#, python-format
msgid "failed to instantiate stack lifecycle class %s"
msgstr "fallo al instanciar clase de ciclo de vida de la pila %s"

#: heat/common/lifecycle_plugin_utils.py:55
msgid "failed to sort lifecycle plug point classes"
msgstr ""
"ha ocurrido un error al ordenar las clases del punto de conexión de ciclo de "
"vida"

#: heat/common/lifecycle_plugin_utils.py:108
#, python-format
msgid "%(opname) %(ci)s failed for %(a)s on %(sid)s"
msgstr "%(opname) %(ci)s fallo por %(a)s en %(sid)s"

#: heat/common/plugin_loader.py:97
#, python-format
msgid "Failed to import module %s"
msgstr "No se ha podido importar el modulo %s"

#: heat/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr "Se está descartando excepción original: %s"

#: heat/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr "La excepción inesperada ha ocurrido %d vez(veces)... reintentando."

#: heat/openstack/common/lockutils.py:120
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr "No se ha podido liberar el bloqueo adquirido `%s`"

#: heat/openstack/common/loopingcall.py:89
msgid "in fixed duration looping call"
msgstr "en llamada en bucle de duración fija"

#: heat/openstack/common/loopingcall.py:131
msgid "in dynamic looping call"
msgstr "en llamada en bucle dinámica"

#: heat/openstack/common/policy.py:507
#, python-format
msgid "Failed to understand rule %s"
msgstr "Ha ocurrido un error al interpretar la regla %s"

#: heat/openstack/common/policy.py:517
#, python-format
msgid "No handler for matches of kind %s"
msgstr "No hay manejador para coincidencias de clase %s"

#: heat/openstack/common/policy.py:787
#, python-format
msgid "Failed to understand rule %r"
msgstr "Ha ocurrido un error al interpretar la regla %r"

#: heat/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr "Excepción durante limpieza de rpc."

#: heat/openstack/common/service.py:277
msgid "Unhandled exception"
msgstr "Excepción no controlada"
